### ISSUE TITLE
Contacts欄を変更

### ISSUE THREAD

**Issue by iorin-io** [yumilc-info/yumilc-info#23]
- Contacts → SNS
- メールを消して、Youtubeを入れる
- スマホの時はテキストを消して横並びに

**Comment by YumiAoki** [comment]
並び順は
X, insta, YouTubeだとうれしいです！
PCのときも文字なしでもOKです。

**Comment by iorin-io** [comment]
テキスト部分が全部`yumILC_`になりそうなので、PCの時もテキストなしにしちゃいます
