### ISSUE TITLE
Works欄の更新

### ISSUE THREAD

**Issue by iorin-io** [yumilc-info/yumilc-info#25]
- TSUKUBA CONNECTの欄を作る
- テキストはもらう
- Tsukuba Place Labとインクルーシブプロジェクトの間に配置

**Comment by YumiAoki** [comment]
TSUKUBA CONNÉCT プログラムリード
大学院生だった2020年からTSUKUBA CONNÉCTへアンバサダーとして参加・登壇し、株式会社しびっくぱわー社員としての配信担当を経て、研究所職員としてプロボノとして参加しています。
https://venturecafetokyo.org/programs/tsukuba-connect/

**Comment by YumiAoki** [comment]
ごめんなさいもう一箇所！サイエンスコミュニケーターのところに最後に一文追加お願いします。

だいたい月1で実験教室「やってみる研究室」実施中！
